---
apiVersion: v1
kind: Description
app: "AWS Fargate"
version: 1.0.0
appVersion: 
  - 1.3.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: 
data: |
    # AWS Fargate
    AWS Fargate is a serverless compute engine for containers that works with both Amazon Elastic Container Service (ECS) and Amazon Elastic Kubernetes Service (EKS).
    
    The metrics for AWS Fargate are obtained through AWS Cloudwatch. Using the [YACE exporter](https://github.com/ivx/yet-another-cloudwatch-exporter). 
    
    # Exporter configuration
    ## Enabling Container Insights
    You need to enable Container Insights to gather metrics for Fargate instance:
    - [How to set up Container Insights on AWS ECS](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS.html)
    - [How to set up Container Insights on AWS EKS and Kubernetes](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-EKS.html)
    
    ## AWS permissions
    The exporter needs permissions to access the resources from the AWS account. 
    
    First, create an AWS IAM policy on your AWS infrastructure allowing read CloudWatch metrics and get resources by tags. 
    Here is a AWS IAM configuration example:
    
    ```
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "CloudWatchExporterPolicy",
                "Effect": "Allow",
                "Action": [
                    "tag:GetResources",
                    "cloudwatch:ListTagsForResource",
                    "cloudwatch:GetMetricStatistics",
                    "cloudwatch:GetMetricData",
                    "cloudwatch:ListMetrics"
                ],
                "Resource": "*"
            }
        ]
    }
    ```
    
    Then, create a file $HOME/.aws/credentials as the following, substituting the values with your key and password: 
    
    ```
    # CREDENTIALS FOR AWS ACCOUNT
    aws_region = us-east-1
    aws_access_key_id = AYYYYYZZZZZZ3BLXXXXX
    aws_secret_access_key = bXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ```
    ## Cloudwatch billing considerations
    Using AWS Cloudwatch for monitoring can incur in additional costs in your AWS billing. 
    Check the [AWS Cloudwatch documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) for further details. 
    
    # Metrics
    Cloudwatch offers the following metrics for AWS Fargate: 
    - ContainerInstanceCount
    - CpuUtilized
    - CpuReserved
    - DeploymentCount
    - DesiredTaskCount
    - MemoryUtilized
    - MemoryReserved
    - NetworkRxBytes
    - NetworkTxBytes
    - PendingTaskCount
    - RunningTaskCount
    - ServiceCount
    - StorageReadBytes
    - StorageWriteBytes
    - TaskCount
    - TaskSetCount
    
    > Note: The metrics NetworkRxBytes and NetworkTxBytes are available only for containers in bridge network mode. 
    
    For further information, consult the [Cloudwatch documentation on Fargate metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html). 