apiVersion: v1
kind: RecordingRule
app: AWS Fargate
version: 1.0.0
appVersion:
- 1.3.0
configurations:
- kind: Prometheus
  data: |-
    - record: aws_ecs_containerinsights_cpu_utilization_rate_average
      expr: avg by (dimension_ServiceName)(aws_ecs_containerinsights_cpu_utilized_average / aws_ecs_containerinsights_cpu_reserved_average)
    - record: aws_ecs_containerinsights_memory_utilization_rate_average
      expr: avg by (dimension_ServiceName)(aws_ecs_containerinsights_memory_utilized_average / aws_ecs_containerinsights_memory_reserved_average)
descriptionFile: RECORDING-RULES.md
