---
apiVersion: v1
kind: RecordingRules
app: "AWS Fargate"
version: 1.0.0
appVersion: 
  - 1.3.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # job:aws_ecs_containerinsights_cpu_utilization_rate:avg
  This rule calculates the CPU utilization by service.
  # job:aws_ecs_containerinsights_memory_utilization_rate:avg
  This rule calculates the memory utilization by service.
data: |
  - record: job:aws_ecs_containerinsights_cpu_utilization_rate:avg
    expr: avg by (dimension_ServiceName)(aws_ecs_containerinsights_cpu_utilized_average / aws_ecs_containerinsights_cpu_reserved_average)
  - record: job:aws_ecs_containerinsights_memory_utilization_rate:avg
    expr: avg by (dimension_ServiceName)(aws_ecs_containerinsights_memory_utilized_average / aws_ecs_containerinsights_memory_reserved_average)