apiVersion: v1
kind: SetupGuide
app: AWS Fargate
version: 1.0.0
appVersion:
- 1.3.0
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Installing the exporter
  To install the exporter follow this steps:

  1. Download the yaml to a local file named 'fargate-deploy.yaml'
  2. Change the following line in the configmap with the AWS region where the resources to monitor are located:
  ```
  region: us-east-1
  ```
  3. Change the field 'credentials' of the secret 'yace-fargate-credentials' and paste the content of the following command:
  ```
  cat ~/.aws/credentials | base64
  ```
  4. Apply the deployment:
  ```
  kubectl apply -f fargate-deploy.yaml
  ```
  5. You can check that the exporter is working checking that the pods are running:
  ```
  kubectl -n yace get pods
  ```
configurations:
- name: fargate-deploy.yaml
  file: include/fargate-deploy.yaml
