apiVersion: v1
data:
  prometheus.yaml: |
    scrape_configs:
    - job_name: 'haproxy'
      metrics_path: /metrics
      params:
        scope:
          - backend
          - frontend
          - global
      sysdig_sd_configs:
      - tags:
          namespace: default
          deployment: haproxy-ingress-kubernetes-ingress
kind: ConfigMap
metadata:
    labels:
      app: sysdig-agent
    name: sysdig-agent
    namespace: sysdig-agent