---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        envFrom:
            - configMapRef:
                name: mongodb-config
            - secretRef:
                name: mongodb-secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  MONGO_INITDB_ROOT_USERNAME: mongodbadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  # Add in MONGO_INITDB_ROOT_PASSWORD the result of:
  # echo -n ADMIN-PASSWORD | base64 
  MONGO_INITDB_ROOT_PASSWORD: ==
