apiVersion: v1
kind: RecordingRule
app: AWS ELB
version: 1.0.0
appVersion:
- 1.0.0
configurations:
- kind: Prometheus
  data: |
    - record: aws_elb_error_rate_4_xx_from_elb_count_sum
      expr: |
        sum(aws_elb_httpcode_elb_4_xx_count_sum or vector(0)) /
        sum(aws_elb_request_count_sum)
    - record: aws_elb_error_rate_5_xx_from_elb_count_sum
      expr: |
        sum(aws_elb_httpcode_elb_5_xx_count_sum or vector(0)) /
        sum(aws_elb_request_count_sum)
    - record: aws_elb_error_rate_4_xx_from_backend_count_sum
      expr: |
        sum(aws_elb_httpcode_backend_4_xx_count_sum or vector(0)) /
        sum(aws_elb_request_count_sum)
    - record: aws_elb_error_rate_5_xx_from_backend_count_sum
      expr: |
        sum(aws_elb_httpcode_backend_5_xx_count_sum or vector(0)) /
        sum(aws_elb_request_count_sum)
descriptionFile: RECORDING-RULES.md
