apiVersion: v1
kind: RecordingRule
app: Kubernetes control plane
version: 1.0.0
appVersion:
- 1.14.0
description: |
  The recording rules for Sysdig, just download it and apply it.
    ```
      kubectl apply -f rules.yaml
    ```
configurations:
- name: rules.yaml
  file: include/rules.yaml
