apiVersion: v1
kind: SetupGuide
app: Kubernetes control plane
version: 1.0.0
appVersion:
- 1.14.0
configurations:
- name: sysdig-agent.yaml
  file: include/sysdig-agent.yaml
- name: prometheus-deploy.yaml
  file: include/prometheus-deploy.yaml
- name: prometheus-cm.yaml
  file: include/prometheus-cm.yaml
descriptionFile: INSTALL.md
