apiVersion: v1
kind: SetupGuide
app: Kubernetes control plane
version: 1.0.0
appVersion:
- 1.14.0
description: |
  # Prerquisites
  To have all metrics in sysdig and because the limit of the timeseries you have to deploy a Prometheus create the recording rules that we later will use to filter only the metrics we need
  So to deploy a Prometheus you will need [helm](https://helm.sh/docs/intro/install/) and [helmfile](https://github.com/roboll/helmfile)

  # Installing the prometheus

  To get the metrics follow this steps:

  1. Install the helm chart with helm file for Prometheus, you have to download the `helmfile.yaml` and the files for the rules `recording_rules.yaml` 
    and to configure the prometheus `prometheus.yaml`
    ```
    helmfile sync
    ```
    ---
    **NOTE**

    If you are using kops, you will have to change the cluster spec to expose the port for the proxy

    ```
    kops --state s3://name-of-s3 --name cluster-name edit cluster
    ```

    And add the follow

    ```
    kubeProxy:
      metricsBindAddress: 0.0.0.0
    ```

    And update the cluster

    ```
    kops --state s3://name-of-s3 --name cluster-name rolling-update cluster --yes
    ```

    ---

  If we want to use the Sysdig agent too, we have to create the recording rules for only scrape the metrics we will use in our dashboards.

  1. Copy the configuration and save it as config.yaml
    ```
    kubectl apply -f sysdig-agent.yaml
    ```
configurations:
- name: helmfile.yaml
  file: include/helmfile.yaml
- name: sysdig-agent.yaml
  file: include/sysdig-agent.yaml
- name: prometheus.yaml
  file: include/prometheus.yaml
- name: recording_rules.yaml
  file: include/recording_rules.yaml
