---
apiVersion: v1
kind: Description
app: "Windows"
version: 1.0.0
appVersion: 
  - 2016
  - 2019
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: 
data: |
    # Windows Management Instrumentation (WMI) 
    The [WMI exporter](https://github.com/martinlindhe/wmi_exporter) offers metrics for instances running Windows operative systems. 
    
    It has a series of different collectors that offer different metrics of the system.
    It can be used as a stand alone application or a Windows service and exposes the metrics in the port 9182 by default.  
    
    # Metrics
    The WMI exporter provides metrics on the following collectors: 
    * CPU: Metrics about CPU usage
    * CS: Hardware of the computer system
    * Logical Disk: Metrics about logical disks 
    * Memory: Metrics about system memory usage
    * Net: Metrics about network interfaces
    * OS: Metrics about the operating system
    * System: Metrics about the system
    
    For further information, consult the [documentation of the WMI exporter](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/README.md). 