---
apiVersion: v1
kind: Alerts
app: "HAProxy Ingress"
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # Alerts
  ## UpTimeLessThan1Hour
  This alert detects when all of the instances of the ingress controller have an uptime of less tha 1 hour.
  
  ## FrontendDown
  This alert detects when a frontend has all of its instances down for more than 10 minutes.
  
  ## BackendDown
  This alert detects when a backend has all of its instances down for more than 10 minutes.
  
  ## HighSessionsUsage
  This alert triggers when the backend sessions overpass the 85% of the sessions capacity for 10 minutes.
  
  ## HigErrorRate 
  This alert triggers when the is an error rate over 15% for over 10 minutes in a proxy.
  
  ## HighRequestDeniedRate and HighResponseDeniedRate
  These alerts detect when there is a denied rate of requests or responses over 10% for over 10 minutes in a proxy.
  
  ## HighResponseTime
  This alert triggers when a proxy has a mean response time higher than 250ms for over 10 minutes.

  # Installing the alerts
  ## In Prometheus
  Copy the alerts for Prometheus and paste them inside of the configuration file in the groups section:
  ```yaml
  [...]
  groups:
  - name: example
      # Insert here the alerts
      rules: 
  ``` 
  ## In Sysdig Monitor
  To install these alerts in Sysdig Monitor, contact with the support service. 
configurations: 
  - kind: Prometheus
    data: |
      - alert: UpTimeLessThan1Hour
        expr: max(time() - haproxy_process_start_time_seconds) < 3600
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: Up Time of less than 1 hour 
      - alert: FrontendDown
        expr: count by (proxy) (haproxy_frontend_status == 1) == 0
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: Frontend down {{$labels.proxy}}
      - alert: BackendDown
        expr: sum by (proxy) (haproxy_backend_status==1) == 0
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: No backend instances found for the proxy {{$labels.proxy}}
      - alert: HighSessionsUsage
        expr: max by (proxy)(rate(haproxy_backend_sessions_total[5m]) / haproxy_backend_limit_sessions) >0.85
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: Low number of sessions available in proxy {{$labels.proxy}}
      - alert: HigErrorRate 
        expr: sum by (proxy)(rate(haproxy_backend_http_responses_total{code!="2xx"}[5m])) / sum by (proxy)(rate(haproxy_backend_http_responses_total[5m])) > 0.15
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: High HTTP error rate in proxy {{$labels.proxy}}
      - alert: HighRequestDeniedRate
        expr: sum by (proxy) (rate(haproxy_backend_requests_denied_total[5m])) / sum by (proxy)(rate(haproxy_backend_http_requests_total[5m])) > 0.15
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: High request denied error rate in proxy {{$labels.proxy}}
      - alert: HighResponseDeniedRate
        expr: sum by (proxy) (rate(haproxy_backend_responses_denied_total[5m])) / sum by (proxy)(rate(haproxy_backend_http_responses_total[5m])) > 0.15
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: High responses denied rate in proxy {{$labels.proxy}}
      - alert: HighResponseTime
        expr: max by (proxy) (haproxy_backend_response_time_average_seconds)> 0.25
        for: 10m
        labels: 
          severity: page
        annotations:
          summary: High response time in proxy {{$labels.proxy}}
  - kind: Sysdig
    data: |
      [
        {
          "alert": {
            "condition": "max(time() - haproxy_process_start_time_seconds) < 3600",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "UpTimeLessThan1Hour",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "count by (proxy) (haproxy_frontend_status == 1) == 0",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "FrontendDown",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "sum by (proxy) (haproxy_backend_status==1) == 0",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "BackendDown",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "max by (proxy)(rate(haproxy_backend_sessions_total[5m]) / haproxy_backend_limit_sessions) >0.85",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "HighSessionsUsage",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "sum by (proxy)(rate(haproxy_backend_http_responses_total{code!=\"2xx\"}[5m])) / sum by (proxy)(rate(haproxy_backend_http_responses_total[5m])) > 0.15",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "HigErrorRate",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "sum by (proxy) (rate(haproxy_backend_requests_denied_total[5m])) / sum by (proxy)(rate(haproxy_backend_http_requests_total[5m])) > 0.15",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "HighRequestDeniedRate",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "sum by (proxy) (rate(haproxy_backend_responses_denied_total[5m])) / sum by (proxy)(rate(haproxy_backend_http_responses_total[5m])) > 0.15",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "HighResponseDeniedRate",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        },
        {
          "alert": {
            "condition": "max by (proxy) (haproxy_backend_response_time_average_seconds)> 0.25",
            "customNotification": {
              "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
              "useNewTemplate": false
            },
            "enabled": true,
            "name": "HighResponseTime",
            "rateOfChange": false,
            "reNotify": false,
            "reNotifyMinutes": "10m",
            "severity": 4,
            "severityLabel": "LOW",
            "severityLevel": null,
            "timespan": 600000000,
            "type": "PROMETHEUS"
          }
        }
      ]
