apiVersion: v1
kind: Description
app: HAProxy Ingress
version: 1.0.0
appVersion:
- '2.1'
maintainers: Configuration files and dashboards maintained by [Sysdig team](https://sysdig.com/).
data: |-
  # HAProxy ingress controller for Kubernetes
  HAProxy ingress controller is a Kubernetes resource that routes traffic from outside your cluster to services within the cluster. this ingress controller uses the HAProxy load balancer.

  # Metrics
  The HAProxy ingress instruments Prometheus metrics on the following scopes:
  - Global
  - Frontend
  - Backend
  - Server (disabled in the configuration provided)

  For a complete list of the metrics exported, consult the [HAProxy exporter documentation](https://github.com/haproxy/haproxy/blob/master/contrib/prometheus-exporter/README)

  # Number of time series generated
  Usually, for the configuration provided, the number of time series is approximately:
  - 150 x number of ingress pods
  - 50 x number of ingress pods x ingress resources

  For further information, consult [HAProxy Kubernetes ingress controller](https://github.com/haproxytech/kubernetes-ingress).
