apiVersion: v1
kind: RecordingRule
app: AWS EBS
version: 1.0.0
appVersion:
- 1.0.0
configurations:
- kind: Prometheus
  data: |
    - record: aws_ebs_volume_read_operation_time_average
      expr: |
        aws_ebs_volume_total_read_time_sum / aws_ebs_volume_read_ops_sum
    - record: aws_ebs_volume_write_operation_time_average
      expr: |
        aws_ebs_volume_total_write_time_sum / aws_ebs_volume_write_ops_sum
descriptionFile: RECORDING-RULES.md
