apiVersion: v1
kind: Alert
app: AWS S3
version: 1.0.0
appVersion:
- 1.0.0
configurations:
- kind: Prometheus
  data: |
    - alert: High4XXErrorRate
      expr: aws_s3_4xx_errors_average > 0.15
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High 4XX error rate on bucket {{$labels.dimension_BucketName}}
    - alert: High5XXErrorRate
      expr: aws_s3_5xx_errors_average > 0.15
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High 5XX error rate on bucket {{$labels.dimension_BucketName}}
    - alert: HighFirstByteLatency
      expr: avg(aws_s3_first_byte_latency_p95) > 250
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High latency on bucket {{$labels.dimension_BucketName}}
- data: |-
    {
      "alert": {
        "condition": "aws_s3_4xx_errors_average > 0.15",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "High4XXErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "aws_s3_5xx_errors_average > 0.15",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "High5XXErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "avg(aws_s3_first_byte_latency_p95) > 250",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighFirstByteLatency",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
descriptionFile: ALERTS.md
