apiVersion: v1
kind: Alert
app: Nginx
version: 1.0.0
appVersion:
- '1.17'
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Alerts
  ## NoIntancesUp
  This alert detects when there is no instances with a certain label 'app' for more than 10 minutes.

configurations:
- kind: Prometheus
  data: |
    - alert: NoIntancesUp
      expr: sum by (app)(nginx_up or vector(0)) == 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: No Nginx instances Up for the app {{$labels.app}}
- data: |-
    {
      "alert": {
        "condition": "sum by (app)(nginx_up or vector(0)) == 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "NoIntancesUp",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
