apiVersion: v1
kind: SetupGuide
app: Nginx
version: 1.0.0
appVersion:
- '1.17'
descriptionFile: INSTALL.md
configurations:
- name: configuration.yaml
  file: include/configuration.yaml
- name: sysdig-agent-config.yaml
  file: include/sysdig-agent-config.yaml
