apiVersion: v1
kind: RecordingRule
app: AWS ALB
version: 1.0.0
appVersion:
- 1.0.0
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # aws_alb_httpcode_elb_4_xx_error_rate_count_sum
  This rule calculates error rate of errors with code 4XX generated in the load balancer.
  # aws_alb_httpcode_elb_5_xx_error_rate_count_sum
  This rule calculates error rate of errors with code 5XX generated in the load balancer.
  # aws_alb_tg_httpcode_target_4_xx_error_rate_count_sum
  This rule calculates error rate of errors with code 4XX generated in the target groups.
  # aws_alb_tg_httpcode_target_5_xx_error_rate_count_sum
  This rule calculates error rate of errors with code 5XX generated in the target groups.
configurations:
- kind: Prometheus
  data: |
    - record: aws_alb_httpcode_elb_4_xx_error_rate_count_sum
      expr: |
        (sum(aws_alb_httpcode_elb_4_xx_count_sum or vector(0))
        /( sum(aws_alb_request_count_sum or vector(0))
         + sum(aws_alb_httpcode_elb_5_xx_count_sum or vector(0))
         + sum(aws_alb_httpcode_elb_4_xx_count_sum or vector(0))
         + sum(aws_alb_httpcode_elb_3_xx_count_sum or vector(0)) > 0)
        or vector(0))
    - record: aws_alb_httpcode_elb_5_xx_error_rate_count_sum
      expr: |
        (sum(aws_alb_httpcode_elb_5_xx_count_sum or vector(0))
        /( sum(aws_alb_request_count_sum or vector(0))
         + sum(aws_alb_httpcode_elb_5_xx_count_sum or vector(0))
         + sum(aws_alb_httpcode_elb_4_xx_count_sum or vector(0))
         + sum(aws_alb_httpcode_elb_3_xx_count_sum or vector(0)) > 0)
        or vector(0))
    - record: aws_alb_tg_httpcode_target_4_xx_error_rate_count_sum
      expr: |
        (sum(aws_alb_tg_httpcode_target_4_xx_count_sum or vector(0))
        / (sum(aws_alb_tg_httpcode_target_2_xx_count_sum or vector(0))
        + sum(aws_alb_tg_httpcode_target_3_xx_count_sum or vector(0))
        + sum(aws_alb_tg_httpcode_target_4_xx_count_sum or vector(0))
        + sum(aws_alb_tg_httpcode_target_5_xx_count_sum or vector(0)) > 0)
        or vector(0))
    - record: aws_alb_tg_httpcode_target_5_xx_error_rate_count_sum
      expr: |
        (sum(aws_alb_tg_httpcode_target_5_xx_count_sum or vector(0))
        / (sum(aws_alb_tg_httpcode_target_2_xx_count_sum or vector(0))
        + sum(aws_alb_tg_httpcode_target_3_xx_count_sum or vector(0))
        + sum(aws_alb_tg_httpcode_target_4_xx_count_sum or vector(0))
        + sum(aws_alb_tg_httpcode_target_5_xx_count_sum or vector(0)) > 0)
        or vector(0))
