apiVersion: v1
kind: SetupGuide
app: AWS ALB
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: INSTALL.md
configurations:
- name: alb-deploy.yaml
  file: include/alb-deploy.yaml
- name: sysdig-agent-config.yaml
  file: include/sysdig-agent-config.yaml

