---
apiVersion: v1
kind: Alerts
app: "Harbor"
version: 1.0.0
appVersion: 
  - 1.1
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # Alerts
    ## HarborIsDown
    This alert trigger when the service is down

    ##  ProjectQuotaIsRaisingTheLimit
    This alerts trigger when the usage of the storage of any project is getting close to the limit

configurations: 
  - kind: Prometheus
    data: |
      - alert: HarborIsDown
        expr: harbor_up == 0
        for: 5m
        labels: 
          severity: critical
        annotations:
          summary: The service of Harbor is Down
      - alert: ProjectQuotaIsRaisingTheLimit
        expr: harbor_quotas_size_bytes{type="used"} / ignoring(type) harbor_quotas_size_bytes{type="hard"} > 0.95
        for: 5m
        labels: 
          severity: critical
        annotations:
          summary: The quota of the repository {{ $labels.repo_name }} is getting close to the limit
