apiVersion: v1
kind: ExporterConfig
app: Harbor
version: 1.0.0
appVersion:
- '1.1'
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Installing the exporter
  To install the exporter follow this steps:

  After installing the helm chart of Harbor as reference:

  ```
    helm install harbor harbor/harbor
  ```

  Install the exporter, with the next configuration

  ```
    kubectl apply -f harbor.yaml
  ```

  ```
    kubectl apply -f sysdig-agent.yaml
  ```
configurations:
- name: harbor.yaml
  file: include/harbor.yaml
