apiVersion: v1
kind: Description
app: Kubernetes resources
version: 1.0.0
appVersion:
- 1.14
maintainers: Configuration files and dashboards maintained by [Sysdig team](https://sysdig.com/).
description: null
data: |-
  # Kubernetes
  Kubernetes (K8s) is an open-source system for automating deployment, scaling, and management of containerized applications.

  The metrics for the information of kubernetes control plane are gathered from the kube-state-metrics exporter and from the node exporter.

  #Prometheus and exporters

  For the instalation of the entire infrastructure you can just install the helm chart of prometheus.
  ```
  helm install stable/prometheus
  ```

  #Metrics
  With this metrics we can see the information about:
