apiVersion: v1
kind: ExporterConfig
app: Kubernetes resources
version: 1.0.0
appVersion:
- 1.14.0
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Installing the exporter
  To install the exporter follow this steps:

  After installing the helm chart of Prometheus as reference:
  ```
  helm install stable/prometheus
  ```
  We have to add the recording rules and alerts rules in the prometheus configuration that we have in the next tabs.
configurations:
- name: configuration.yaml
  file: include/configuration.yaml
