apiVersion: v1
kind: SetupGuide
app: Kubernetes resources
version: 1.0.0
appVersion:
- 1.14.0
configurations:
- name: configuration.yaml
  file: include/configuration.yaml
descriptionFile: INSTALL.md
