---
apiVersion: v1
kind: Description
app: "AWS EC2"
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: 
data: |
    # AWS EC2
    Amazon Elastic Compute Cloud (Amazon EC2) provides scalable computing capacity in the Amazon Web Services (AWS) cloud.

    The metrics for AWS EC2 are obtained through AWS Cloudwatch. Using the [YACE exporter](https://github.com/ivx/yet-another-cloudwatch-exporter). 

    # Exporter configuration
    ## AWS permissions
    The exporter needs permissions to access the resources from the AWS account. 

    First, create an AWS IAM policy on your AWS infrastructure allowing read CloudWatch metrics and get resources by tags. 
    Here is a AWS IAM configuration example:

    ```
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "CloudWatchExporterPolicy",
                "Effect": "Allow",
                "Action": [
                    "tag:GetResources",
                    "cloudwatch:ListTagsForResource",
                    "cloudwatch:GetMetricStatistics",
                    "cloudwatch:GetMetricData",
                    "cloudwatch:ListMetrics"
                ],
                "Resource": "*"
            }
        ]
    }
    ```

    Then, create a file $HOME/.aws/credentials as the following, substituting the values with your key and password: 

    ```
    # CREDENTIALS FOR AWS ACCOUNT
    aws_region = us-east-1
    aws_access_key_id = AYYYYYZZZZZZ3BLXXXXX
    aws_secret_access_key = bXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ```

    ## Cloudwatch billing considerations
    Using AWS Cloudwatch for monitoring can incur in additional costs in your AWS billing. 
    Check the [AWS Cloudwatch documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) for further details. 

    # Metrics
    ## Status Check Metrics
    - StatusCheckFailed
    - StatusCheckFailed_Instance
    - StatusCheckFailed_System

    ## Instance Metrics
    - CPUUtilization
    - DiskReadOps
    - DiskWriteOps
    - DiskReadBytes (Divide by 300 to get bytes per second)
    - DiskWriteBytes (Divide by 300 to get bytes per second)
    - NetworkIn (Divide by 300 to get bytes per second)
    - NetworkOut (Divide by 300 to get bytes per second)
    - NetworkPacketsIn
    - NetworkPacketsOut
    - MetadataNoToken

    ## CPU Credit Metrics
    These metrics are available only for burstable performance instances
    - CPUCreditUsage
    - CPUCreditBalance
    - CPUSurplusCreditBalance
    - CPUSurplusCreditsCharged

    ## EBS Metrics for Nitro-based Instances
    These metrics are only available for Nitro-based instances
    - EBSReadOps
    - EBSWriteOps
    - EBSReadBytes
    - EBSWriteBytes
    - EBSIOBalance%
    - EBSByteBalance%

    For further information, consult the [Cloudwatch documentation on EC2 metrics](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html). 