---
apiVersion: v1
kind: ExporterConfig
app: "AWS EC2"
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # Installing the exporter
  To install the exporter follow this steps:

  1. Download the yaml to a local file named 'ec2-deploy.yaml'
  2. Change the following lines in the configmap with the AWS region where the resources to monitor are located:
  ```
  region: us-east-1
  ```
  3. Change the field 'credentials' of the secret 'yace-ec2-credentials' and paste the content of the following command:
  ```
  cat ~/.aws/credentials | base64
  ```
  4. Apply the deployment:
  ```
  kubectl apply -f ec2-deploy.yaml
  ```
  5. You can check that the exporter is working checking that the pods are running:
  ```
  kubectl -n yace get pods
  ```
data: |
  apiVersion: v1
  kind: Namespace
  metadata:
    name: yace
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: yace-ec2
    namespace: yace    
  spec:
    selector:
      matchLabels:
        app: yace-ec2
    replicas: 1
    template:
      metadata:
        labels:
          app: yace-ec2
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "5000"
      spec:
        containers:
        - name: yace
          image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.15.0-alpha
          ports:
          - containerPort: 5000
          volumeMounts:
            - name: yace-ec2-config
              mountPath: /tmp/config.yml
              subPath: config.yml
            - name: yace-ec2-credentials
              mountPath: /exporter/.aws/credentials
              subPath: credentials
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        volumes:
          - configMap:
              defaultMode: 420
              name: yace-ec2-config
            name: yace-ec2-config
          - secret:
              defaultMode: 420
              secretName: yace-ec2-credentials
            name: yace-ec2-credentials
  ---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: yace-ec2-config
    namespace: yace
  data:
    config.yml: |
      discovery:
        jobs:
        - region: us-east-1
          type: s3
          metrics: 
            - name: NumberOfObjects
              statistics:
                - Average
              period: 86400
              length: 172800
              additionalDimensions:
                - name: StorageType
                  value: AllStorageTypes
            - name: BucketSizeBytes
              statistics:
                - Average
              period: 86400
              length: 172800
              additionalDimensions:
                - name: StorageType
                  value: StandardStorage
        - region: us-east-1
          type: s3
          awsDimensions: 
            - FilterId
          metrics: 
            - name: AllRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: GetRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: PutRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: DeleteRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: HeadRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: PostRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: SelectRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: SelectScannedBytes
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: SelectReturnedBytes
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: ListRequests
              statistics:
                - Sum
              period: 60  
              length: 3600
            - name: BytesDownloaded
              statistics:
                - Sum
                - Average
              period: 60  
              length: 3600
            - name: BytesUploaded
              statistics:
                - Sum
                - Average
              period: 60  
              length: 3600
            - name: 4xxErrors
              statistics:
                - Sum
                - Average
              period: 60  
              length: 3600
            - name: 5xxErrors
              statistics:
                - Sum
                - Average
              period: 60  
              length: 3600
            - name: FirstByteLatency
              statistics:
                - Average
              period: 60  
              length: 3600
            - name: TotalRequestLatency
              statistics:
                - Average
              period: 60  
              length: 3600
            - name: ReplicationLatency
              statistics:
                - Maximum
              period: 60  
              length: 3600
            - name: BytesPendingReplication
              statistics:
                - Maximum
              period: 60  
              length: 3600
            - name: OperationsPendingReplication
              statistics:
                - Maximum
              period: 60  
              length: 3600      
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: yace-ec2-credentials
    namespace: yace
  data:
    # Add in credentials the result of: 
    # cat ~/.aws/credentials | base64
    credentials: |
      XXXXX
