apiVersion: v1
kind: Alert
app: AWS Lambda
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: ALERTS.md

configurations:
- kind: Prometheus
  data: |
    - alert: HighFunctionErrorRate
      expr: (aws_lambda_errors_sum / aws_lambda_invocations_sum) > 0.15
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High error rate on function {{$labels.dimension_FunctionName}}
    - alert: ThrottlingFunction
      expr: aws_lambda_throttles_sum  > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected throttling in function {{$labels.dimension_FunctionName}}
    - alert: DestinationDeliveryFailures
      expr: aws_lambda_destination_delivery_failures_sum > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected destination delivery failures in function {{$labels.dimension_FunctionName}}
    - alert: DeadLetterErrors
      expr: aws_lambda_dead_letter_errors_sum  > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected dead-letter queue errors in function {{$labels.dimension_FunctionName}}
    - alert: HighIteratorAge
      expr: aws_lambda_iterator_age_average  > 1000
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected high iterator age in function {{$labels.dimension_FunctionName}}
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(aws_lambda_errors_sum / aws_lambda_invocations_sum) > 0.15",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighFunctionErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_throttles_sum  > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "ThrottlingFunction",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_destination_delivery_failures_sum > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "DestinationDeliveryFailures",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_dead_letter_errors_sum  > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "DeadLetterErrors",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_iterator_age_average  > 1000",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighIteratorAge",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
