apiVersion: v1
kind: Alert
app: AWS Lambda
version: 1.0.0
appVersion:
- 1.0.0
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Alerts
  ## HighFunctionErrorRate
  A Lambda function can end with an error.
  This alert triggers when the percentage of executions of a function excess a threshold for a certain period of time.

  The recommended value for this alert is 15% of the functions ended with error for 10 minutes.

  ## ThrottlingFunction
  Lambda has a limited number of concurrent executions per function.
  When you reach this limit, the function cannot be executed. The metric 'throttled' gives information of the executions that were not executed because they reached the concurrency limit.
  Constant throttling can indicate that a function is called more times that its reserved concurrency.

  The recommended value for this alert is to alert when throttling for more than 10 minutes.

  ## DestinationDeliveryFailures
  Detected destination delivery failures in a function.

  ## DeadLetterErrors
  Detected dead-letter queue errors in a function.

  ## HighIteratorAge
  Detected high iterator age in a function.

configurations:
- kind: Prometheus
  data: |
    - alert: HighFunctionErrorRate
      expr: (aws_lambda_errors_sum / aws_lambda_invocations_sum) > 0.15
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High error rate on function {{$labels.dimension_FunctionName}}
    - alert: ThrottlingFunction
      expr: aws_lambda_throttles_sum  > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected throttling in function {{$labels.dimension_FunctionName}}
    - alert: DestinationDeliveryFailures
      expr: aws_lambda_destination_delivery_failures_sum > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected destination delivery failures in function {{$labels.dimension_FunctionName}}
    - alert: DeadLetterErrors
      expr: aws_lambda_dead_letter_errors_sum  > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected dead-letter queue errors in function {{$labels.dimension_FunctionName}}
    - alert: HighIteratorAge
      expr: aws_lambda_iterator_age_average  > 1000
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Detected high iterator age in function {{$labels.dimension_FunctionName}}
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(aws_lambda_errors_sum / aws_lambda_invocations_sum) > 0.15",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighFunctionErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_throttles_sum  > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "ThrottlingFunction",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_destination_delivery_failures_sum > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "DestinationDeliveryFailures",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_dead_letter_errors_sum  > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "DeadLetterErrors",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "aws_lambda_iterator_age_average  > 1000",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighIteratorAge",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
