---
apiVersion: v1
kind: Description
app: "AWS Lambda"
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: sysdiglabs
    link: https://github.com/sysdiglabs
description: 
data: |
    # AWS Lambda
    AWS Lambda lets you run code without provisioning or managing servers.With Lambda, you can run code for virtually any type of application or backend service - all with zero administration. Just upload your code and Lambda takes care of everything required to run and scale your code with high availability. You can set up your code to automatically trigger from other AWS services or call it directly from any web or mobile app..
    
    The metrics for AWS Fargate are obtained through AWS Cloudwatch. Using the [YACE exporter](https://github.com/ivx/yet-another-cloudwatch-exporter). 
    
    # Exporter configuration
    ## AWS permissions
    The exporter needs permissions to access the resources from the AWS account. 
    
    First, create an AWS IAM policy on your AWS infrastructure allowing read CloudWatch metrics and get resources by tags. Here is a AWS IAM configuration example:
    
    ```
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "CloudWatchExporterPolicy",
                "Effect": "Allow",
                "Action": [
                    "tag:GetResources",
                    "cloudwatch:ListTagsForResource",
                    "cloudwatch:GetMetricStatistics",
                    "cloudwatch:ListMetrics"
                ],
                "Resource": "*"
            }
        ]
    }
    ```
        
    Then, create a file $HOME/.aws/credentials as the following, substituting the values with your key and password: 
    
    ```
    # CREDENTIALS FOR AWS ACCOUNT
    aws_region = us-east-1
    aws_access_key_id = AYYYYYZZZZZZ3BLXXXXX
    aws_secret_access_key = bXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ```
    ## Cloudwatch billing considerations
    Using AWS Cloudwatch for monitoring can incur in additional costs in your AWS billing. Check the [AWS Cloudwatch documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) for further details. 
    
    # Metrics
    Cloudwatch offers the following metrics for AWS Lambda: 
    - Invocations
    - Errors
    - Throttles
    - Duration
    
    
    For further information, consult the [Cloudwatch documentation on Lambda metrics](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html). 