apiVersion: v1
kind: ExporterConfig
app: AWS Lambda
version: 1.0.0
appVersion:
- 1.0.0
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Installing the exporter
  To install the exporter follow this steps:

  1. Download the yaml to a local file named 'lambda-deploy.yaml'
  2. Change the following line in the configmap with the AWS region where the resources to monitor are located:
  ```
  region: us-east-1
  ```
  3. Change the field 'credentials' of the secret 'yace-lambda-credentials' and paste the content of the following command:
  ```
  cat ~/.aws/credentials | base64
  ```
  4. Apply the deployment:
  ```
  kubectl apply -f lambda-deploy.yaml
  ```
  5. You can check that the exporter is working checking that the pods are running:
  ```
  kubectl -n yace get pods
  ```
configurations:
- name: lambda-deploy.yaml
  data: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: yace
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: yace-lambda
      namespace: yace
    spec:
      selector:
        matchLabels:
          app: yace-lambda
      replicas: 1
      template:
        metadata:
          labels:
            app: yace-lambda
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "5000"
        spec:
          containers:
          - name: yace
            image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.16.0-alpha
            ports:
            - containerPort: 5000
            volumeMounts:
              - name: yace-lambda-config
                mountPath: /tmp/config.yml
                subPath: config.yml
              - name: yace-lambda-credentials
                mountPath: /exporter/.aws/credentials
                subPath: credentials
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
          volumes:
            - configMap:
                defaultMode: 420
                name: yace-lambda-config
              name: yace-lambda-config
            - secret:
                defaultMode: 420
                secretName: yace-lambda-credentials
              name: yace-lambda-credentials
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: yace-lambda-config
      namespace: yace
    data:
      config.yml: |
        discovery:
          jobs:
          - region: us-east-1
            type: lambda
            enableMetricData: true
            metrics:
              - name: Duration
                statistics:
                - Sum
                - Maximum
                - Minimum
                - Average
                period: 600
                length: 300
              - name: Invocations
                statistics:
                - Sum
                period: 600
                length: 300
              - name: Errors
                statistics:
                - Sum
                period: 600
                length: 300
              - name: Throttles
                statistics:
                - Sum
                period: 600
                length: 300
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: yace-lambda-credentials
      namespace: yace
    data:
      # Add in credentials the result of:
      # cat ~/.aws/credentials | base64
      credentials: |
        XXXXX
