---
apiVersion: v1
kind: RecordingRules
app: "AWS Lambda"
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # job:aws_lambda_error_rate:avg
  This rule calculates the error rate by function.
data: |
  - record: job:aws_lambda_error_rate:avg
    expr: avg by (dimension_FunctionName)(aws_lambda_errors_sum / aws_lambda_invocations_sum)
  