---
apiVersion: v1
kind: RecordingRule
app: "AWS Lambda"
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # aws_lambda_error_rate_average
  This rule calculates the error rate by function.
data: |
  - record: aws_lambda_error_rate_average
    expr: avg by (dimension_FunctionName)(aws_lambda_errors_sum / aws_lambda_invocations_sum)
  