---
apiVersion: v1
kind: ExporterConfig
app: "Istio"
version: 1.0.0
appVersion: 
  - 1.5
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # Installing the exporter
  In the case of Istio, the components are exporters and have the endpoint, when we install the istio 
  with the tool istioctl we are installing a prometheus with the configuration to get all targets

  If we want the targets in our prometheus the simplest way to do it is federate the prometheus, another
  way to do this is anotate all pods and sidecars which is a lot of work and you can probably miss 
  something
data: |