apiVersion: v1
kind: Description
app: 'etcd'
version: 1.0.0
appVersion:
  - '3.4.0'
maintainers: Configuration files and dashboards maintained by [Sysdig team](https://sysdig.com/).
data: |-
  # etcd is a strongly consistent, distributed key-value store that provides a reliable way to store data that needs to be accessed by a distributed system or cluster of machines. 
  It gracefully handles leader elections during network partitions and can tolerate machine failure, even in the leader node.

  Etcd is the core of any Kubernetes cluster so it is so important to monitor it, hopefully etcd expose all their metrics with Prometheus format so we only have to configure the Prometheus job that does it. 
  # Metrics
  * Etcd has a leader?
  * The number of leader changes seen
  * The total number of failed proposals seen
  * RPC Rate
  * Active Streams
  * DB Size
  * Disk Sync Duration
  * The total number of consensus proposals committed
  * Memory
  * CPU usage
  * Goroutines

  # Source
  The alerts are inspired from [monitoring mixin](https://monitoring.mixins.dev/etcd/)
