apiVersion: v1
kind: SetupGuide
app: etcd
version: 1.0.0
appVersion:
- 3.4.0
configurations:
- name: etcd-rules.yaml
  file: include/etcd-rules.yaml
- name: sysdig-agent-example.yaml
  file: include/sysdig-agent-example.yaml
- name: prometheus-cm.yaml
  file: include/prometheus-cm.yaml
descriptionFile: INSTALL.md
