---
apiVersion: v1
kind: Description
app: ""
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
data: |
    # 
    
    # Metrics

    # Number of time series generated

    
    For further information, consult [...](https://). 