---
apiVersion: v1
kind: ExporterConfig
app: ""
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # Installing the exporter
  
  # Sysdig Agent configuration

data: |
  #