---
apiVersion: v1
kind: RecordingRules
app: ""
version: 1.0.0
appVersion: 
  - 1.0.0
maintainers:
  - name: Sysdig team
    link: https://sysdig.com/
description: |
  # ruleXXX
  This rule...

data: |
  #
