apiVersion: v1
kind: SetupGuide
app: ''
version: 1.0.0
appVersion:
- 1.0.0
description: |
  # Installing the exporter

  # Sysdig Agent configuration
configurations:
- name: configuration.yaml
  file: include/configuration.yaml
