apiVersion: v1
kind: Alert
app: WMI
version: 1.0.0
appVersion:
- '2016'
- '2019'
configurations:
- kind: Prometheus
  data: |
    - alert: HighCPUUsage
      expr: 100 * sum by (instance) (rate(wmi_cpu_time_total{mode != 'idle'}[5m])) / count by (instance) (wmi_cpu_core_frequency_mhz) > 95
      for: 15m
      labels:
        severity: page
      annotations:
        summary: High CPU usage in instance {{$labels.instance}}
    - alert: HighPhysicalMemoryUsage
      expr: 100 * (wmi_cs_physical_memory_bytes - wmi_os_physical_memory_free_bytes) / wmi_cs_physical_memory_bytes  > 95
      for: 15m
      labels:
        severity: page
      annotations:
        summary: High physical memory usage in instance {{$labels.instance}}
    - alert: LogicalDiskFull
      expr: 100 * (wmi_logical_disk_size_bytes - wmi_logical_disk_free_bytes) / wmi_logical_disk_size_bytes  > 95
      for: 15m
      labels:
        severity: page
      annotations:
        summary: Disk {{$labels.volume}} full over 95% in instance {{$labels.instance}}
    - alert: UpTimeLessThanOneHour
      expr: time() - wmi_system_system_up_time  < 3600
      for: 15m
      labels:
        severity: page
      annotations:
        summary: Up Time of less than 1 hour in instance {{$labels.instance}}
    - alert: HighInboundErrorRate
      expr: 100 * rate(wmi_net_packets_received_errors[5m]) / (rate(wmi_net_packets_received_errors[5m]) + rate(wmi_net_packets_received_total[5m])>0)  > 75
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High inbound network error rate in instance {{$labels.instance}}
    - alert: HighOutboundErrorRate
      expr: 100 * rate(wmi_net_packets_outbound_errors[5m]) / (rate(wmi_net_packets_outbound_errors[5m]) + rate(wmi_net_packets_sent_total[5m])>0)  > 75
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High outbound network error rate in instance {{$labels.instance}}
- data: |-
    {
      "alert": {
        "condition": "100 * sum by (instance) (rate(wmi_cpu_time_total{mode != 'idle'}[5m])) / count by (instance) (wmi_cpu_core_frequency_mhz) > 95",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighCPUUsage",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "100 * (wmi_cs_physical_memory_bytes - wmi_os_physical_memory_free_bytes) / wmi_cs_physical_memory_bytes  > 95",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighPhysicalMemoryUsage",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "100 * (wmi_logical_disk_size_bytes - wmi_logical_disk_free_bytes) / wmi_logical_disk_size_bytes  > 95",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "LogicalDiskFull",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "time() - wmi_system_system_up_time  < 3600",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "UpTimeLessThanOneHour",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "100 * rate(wmi_net_packets_received_errors[5m]) / (rate(wmi_net_packets_received_errors[5m]) + rate(wmi_net_packets_received_total[5m])>0)  > 75",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighInboundErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
- data: |-
    {
      "alert": {
        "condition": "100 * rate(wmi_net_packets_outbound_errors[5m]) / (rate(wmi_net_packets_outbound_errors[5m]) + rate(wmi_net_packets_sent_total[5m])>0)  > 75",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighOutboundErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
  kind: Sysdig
descriptionFile: ALERTS.md
