---
apiVersion: v1
kind: App
name: "Apache Solr"
keywords: 
  - database
availableVersions: 
  - 8.4
shortDescription: "Solr is an open-source enterprise-search platform."
description: |
  Solr is an open-source enterprise-search platform, written in Java, from the Apache Lucene project. 
icon: https://upload.wikimedia.org/wikipedia/en/b/bb/Apache_Solr_Logo.svg
website: https://lucene.apache.org/solr/
available: false