---
apiVersion: v1
kind: App
name: "AWS S3"
keywords: 
  - aws
  - storage
availableVersions: 
  - 1.0.0
shortDescription: AWS Object storage
description: |
  # AWS S3
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/500px-Amazon_Web_Services_Logo.svg.png
website: https://aws.amazon.com/s3/
available: true