---
apiVersion: v1
kind: App
name: "AWS ElastiCache"
keywords: 
  - aws
  - database
availableVersions: 
  - 1.5.10
shortDescription: AWS Fully managed in-memory data store, compatible with Redis or Memcached.
description: |
  # AWS ElastiCache
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/500px-Amazon_Web_Services_Logo.svg.png
website: https://aws.amazon.com/elasticache/
available: false