---
apiVersion: v1
kind: App
name: "AWS EBS"
keywords: 
  - aws
  - platform
  - available
availableVersions: 
  - 1.0.0
shortDescription: AWS Elastic Block Store
description: |
  # AWS EBS
icon: https://raw.githubusercontent.com/sysdiglabs/promcat-resources/master/apps/images/aws-ebs.png
website: https://aws.amazon.com/ebs/
available: true