---
apiVersion: v1
kind: App
name: "AWS Lambda"
keywords: 
  - AWS
  - Platform
  - Serverless
  - Available
availableVersions: 
  - 1.0.0
shortDescription: AWS serverless functions
description: |
  # AWS Lambda
icon: https://raw.githubusercontent.com/sysdiglabs/promcat-resources/master/apps/images/aws-lambda.png
website: https://aws.amazon.com/lambda/
available: true