---
apiVersion: v1
kind: App
name: "Kubernetes resources"
keywords: 
  - kubernetes
  - coming soon
availableVersions: 
  - 1.14.0
shortDescription: Open-source system for automating deployment, scaling, and management of containerized applications.
description: |
  # Kubernetes (K8s) resoureces monitor. 
icon: https://upload.wikimedia.org/wikipedia/commons/6/67/Kubernetes_logo.svg
website: https://kubernetes.io/
available: false
