---
apiVersion: v1
kind: App
name: "vmware esxi"
keywords:
  - host
availableVersions: 
  - 1
shortDescription: "Collect metrics from ESXi Host."
description: |
  Collect metrics from VmWare ESXi Host.
icon: https://upload.wikimedia.org/wikipedia/commons/9/9a/Vmware.svg
website: https://github.com/devinotelecom/prometheus-vmware-exporter
available: false