---
apiVersion: v1
kind: App
name: "WMI"
keywords: 
  - host
  - windows
availableVersions: 
  - 0.10
shortDescription: "Prometheus exporter for Windows machines."
description: |
  Prometheus exporter for Windows machines, using the WMI (Windows Management Instrumentation).
icon: https://upload.wikimedia.org/wikipedia/commons/8/8d/Windows_darkblue_2012.svg
website: https://github.com/martinlindhe/wmi_exporter
available: false