apiVersion: v1
kind: ExporterConfig
app: Open Policy Agent
version: 1.0.0
appVersion:
- 0.20.4
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: "# Installing the exporter\nGatekeeper exposes a Prometheus metrics endpoint\
  \ to provide metrics for monitoring service health and performance. Open Policy\
  \ Agent also exposes a metrics endpoint when running as a server, but since Gatekeeper\
  \ embeds OPA and we don\u2019t run it as a server, we won\u2019t be using it.\n\n\
  When installing Gatekeeper, you must either edit the Gatekeeper controller manager\
  \ deployment or the service with the appropriate annotations for Prometheus scraping\n\
  \n```\nkubectl -n gatekeeper-system patch deploy gatekeeper-controller-manager -p\
  \ '{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"prometheus.io/scrape\"\
  : \"true\", \"prometheus.io/port\": \"8888\"}}}}}'\nkubectl -n gatekeeper-system\
  \ patch deploy gatekeeper-audit -p '{\"spec\":{\"template\":{\"metadata\":{\"annotations\"\
  :{\"prometheus.io/scrape\": \"true\", \"prometheus.io/port\": \"8888\"}}}}}'\n```\n\
  \n# Sysdig Agent configuration\n\nThen, if you have configured your Prometheus server\
  \ or your [Sysdig agent for Prometheus metric collection](https://docs.sysdig.com/en/integrate-prometheus-metrics.html),\
  \ you should be already ingesting your Gatekeeper metrics.\n"
configurations:
- name: configuration.yaml
  file: include/configuration.yaml
