---
apiVersion: v1
kind: Description
app: "AWS Fargate"
version: 1.0.0
appVersion: 
    - 1.0.0
    - 1.0.1
maintainers:
  - name: sysdiglabs
    link: https://github.com/sysdiglabs
description: 
data: | 
    # ElasticSearch
    Elasticsearch is a distributed, open source search and analytics engine for all types of data, including textual, numerical, geospatial, structured, 
    and unstructured. Elasticsearch is built on Apache Lucene and was first released in 2010 by Elasticsearch N.V. (now known as Elastic). 
    Known for its simple REST APIs, distributed nature, speed, and scalability, Elasticsearch is the central component of the Elastic Stack, 
    a set of open source tools for data ingestion, enrichment, storage, analysis, and visualization. Commonly referred to as the ELK Stack 
    (after Elasticsearch, Logstash, and Kibana), the Elastic Stack now includes a rich collection of lightweight shipping agents known as Beats 
    for sending data to Elasticsearch.
