apiVersion: v1
kind: ExporterConfig
app: 'redis'
version: 1.0.0
appVersion:
  - '<=6'
maintainers:
- name: Sysdig team
  link: https://sysdig.com/
description: |
  # Installing the exporter
  We will use he [Prometheus Redis Metrics Exporter](https://github.com/oliver006/redis_exporter).
  In the file below, you can find a deployment with the exporter as a sidecar of a redis instance.

  To deploy it, just download the file and run:
  ```
  kubectl apply -f redis-deploy.yaml
  ```

  # Sysdig Agent configuration
  No need for special configuration in the agent. 
  Just, be sure to annotate the deployment with the prometheus tags as shown in the deployment file below.

configurations:
- name: redis-deploy.yaml
  data: |
    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: default
      name: redis
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9121"
          labels:
            app: redis
        spec:
          containers:
          - name: redis
            image: redis:4
            ports:
            - containerPort: 6379
          - name: redis-exporter
            image: oliver006/redis_exporter:latest
            ports:
            - containerPort: 9121

